farmakami/urls.py
from django.contrib import admin
from django.urls import path, include

import homepage.urls
import apotek.urls
import produk_apotek.urls
import login.urls
import alat_medis.urls
import balai_pengobatan.urls
import list_produk.urls
import obat.urls
import pengantaran_farmasi.urls
import profil.urls
import transaksi_pembelian.urls
import transaksi_resep.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(homepage.urls)),
    path('apotek/',include(apotek.urls)),
    path('produk_apotek/',include(produk_apotek.urls)),
    path('auth/',include(login.urls)),
    path('alat_medis/',include(alat_medis.urls)),
    path('balai_pengobatan/',include(balai_pengobatan.urls)),
    path('list_produk/',include(list_produk.urls)),
    path('obat/',include(obat.urls)),
    path('pengantaran_farmasi/',include(pengantaran_farmasi.urls)),
    path('profil/',include(profil.urls)),
    path('transaksi_pembelian/',include(transaksi_pembelian.urls)),
    path('transaksi_resep/',include(transaksi_resep.urls))
]

obat/urls.py
from django.urls import path
from .views import *

app_name = 'obat'
urlpatterns = [
	path('', rud_obat, name = 'rud_obat'),
	path('create_obat', create_obat, name = 'create_obat'),
	path('update_obat/<str:key>', update_obat, name = 'update_obat'),
	path('delete_obat/<str:key>', delete_obat, name = 'delete_obat')
]

profil/urls.py
from django.urls import path
from .views import *

app_name = 'profil'
urlpatterns = [
	path('', profil, name='profil')
]

transaksi_resep/urls.py
from django.urls import path
from .views import *

app_name = 'transaksi_resep'
urlpatterns = [
	path('', transaksi_dengan_resep, name='transaksi_dengan_resep'),
	path('create_transaksi_resep', create_transaksi_resep, name='create_transaksi_resep'),
	path('update_transaksi_resep/<str:no_resep>', update_transaksi_resep, name='update_transaksi_resep'),
	path('delete_transaksi_resep/<str:no_resep>', delete_transaksi_resep, name='delete_transaksi_resep')
]

transaksi_resep/models.py
from django.db import models

# Create your models here.

transaksi_resep/forms.py
from django import forms
from django.db import connection


lst_status = ['Entered','Processing','Done']
tuple_status =  [tuple([x,x]) for x in lst_status]

search_path = "SET search_path to FARMAKAMI"

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def get_id_transaksi():
    with connection.cursor() as c:
        c.execute(search_path)
        c.execute("SELECT id_transaksi_pembelian FROM transaksi_pembelian ORDER BY id_transaksi_pembelian ASC")
        res = dictfetchall(c)
    temp_res = [res[i]['id_transaksi_pembelian'] for i in range(len(res))]
    return [tuple([i,i]) for i in temp_res]

def get_email_apoteker():
    with connection.cursor() as c:
        c.execute(search_path)
        c.execute("SELECT email FROM apoteker ORDER BY email ASC")
        res = dictfetchall(c)
    temp_res = [res[i]['email'] for i in range(len(res))]
    return [tuple([i,i]) for i in temp_res]

class createForm(forms.Form):

    nama_dokter = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nama Dokter',
        'type' : 'text',
        'required': True,
    }))

    nama_pasien = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nama Pasien',
        'type' : 'text',
        'required': True,
    }))

    isi_resep = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Isi Resep',
        'type' : 'text',
        'required': True,
    }))

    unggahan_resep = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'Unggahan Resep',
    }), required = False)

    tanggal_resep = forms.DateField(widget=forms.DateInput(attrs={
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'YYYY-MM-DD',
        'required': True,
    }))

    no_telepon = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nomor Telepon Pasien',
        'type' : 'text',
    }), required = False)

    id_transaksi_pembelian = forms.CharField(label="ID Transaksi", widget=forms.Select(choices=get_id_transaksi())) 


class updateForm(forms.Form):

    no_resep = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type' : 'text',
        'required': True,
        'readonly' : True,
    }))

    nama_dokter = forms.CharField( widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nama Dokter',
        'type' : 'text',
        'required': True,
    }))

    nama_pasien = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nama Pasien',
        'type' : 'text',
        'required': True,
    }))

    isi_resep = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Isi Resep',
        'type' : 'text',
        'required': True,
    }))

    unggahan_resep = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'Unggahan Resep',
    }), required = False)

    tanggal_resep = forms.DateField(widget=forms.DateInput(attrs={
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'YYYY-MM-DD',
        'required': True,
    }))

    status_validasi = forms.CharField(label="Status", widget=forms.Select(choices=tuple_status))

    no_telepon = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nomor Telepon Pasien',
        'type' : 'text',
    }), required = False)

    id_transaksi_pembelian = forms.CharField(label="ID Transaksi", widget=forms.Select(choices=get_id_transaksi())) 

    email_apoteker = forms.CharField(label="Email Apoteker", widget=forms.Select(choices=get_email_apoteker()))

transaksi_resep/views.py
from django.shortcuts import render
from django.db import connection
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import *

# Create your views here.
def transaksi_dengan_resep(request):
	with connection.cursor() as c:
		c.execute("SELECT * FROM TRANSAKSI_DENGAN_RESEP ORDER BY no_resep ASC")
		res = dictfetchall(c)
	response = {'data_transaksi_dengan_resep':res}
	return render(request,'transaksi_dengan_resep.html',response)

def create_transaksi_resep(request):
	if request.method == 'POST':
		form = createForm(request.POST)
		if form.is_valid():
			with connection.cursor() as c:
				c.execute("SELECT * FROM TRANSAKSI_DENGAN_RESEP ORDER BY no_resep DESC LIMIT 1")
				last_data = dictfetchall(c)
			last_no_resep = last_data[0]['no_resep']
			updated_last_no_resep = int(last_no_resep[3:])+1
			updated_last_no_resep_str = '{:03d}'.format(updated_last_no_resep)
			no_resep = 'RSP' + updated_last_no_resep_str
			nama_dokter = form.cleaned_data['nama_dokter']
			nama_pasien = form.cleaned_data['nama_pasien']
			isi_resep = form.cleaned_data['isi_resep']
			unggahan_resep = form.cleaned_data['unggahan_resep']
			tanggal_resep = form.cleaned_data['tanggal_resep']
			status_validasi = 'Entered'
			no_telepon = form.cleaned_data['no_telepon']
			id_transaksi_pembelian = form.cleaned_data['id_transaksi_pembelian']
			with connection.cursor() as c:
				c.execute("INSERT INTO TRANSAKSI_DENGAN_RESEP VALUES ( %s, %s, %s, %s, %s, %s, %s, %s, %s, NULL)",
					[no_resep,nama_dokter,nama_pasien,isi_resep,unggahan_resep,tanggal_resep,status_validasi,no_telepon,id_transaksi_pembelian])
		return HttpResponseRedirect(reverse('transaksi_resep:transaksi_dengan_resep'))
	create_form_resep = createForm()
	response = {'create_form_resep':create_form_resep}
	return render(request,'create_transaksi_resep.html',response)

def update_transaksi_resep(request, no_resep):
	if request.method == 'POST':
		form = updateForm(request.POST)
		if form.is_valid():
			no_resep = form.cleaned_data['no_resep']
			nama_dokter = form.cleaned_data['nama_dokter']
			nama_pasien = form.cleaned_data['nama_pasien']
			isi_resep = form.cleaned_data['isi_resep']
			unggahan_resep = form.cleaned_data['unggahan_resep']
			tanggal_resep = form.cleaned_data['tanggal_resep']
			status_validasi = form.cleaned_data['status_validasi']
			no_telepon = form.cleaned_data['no_telepon']
			id_transaksi_pembelian = form.cleaned_data['id_transaksi_pembelian']
			email_apoteker = form.cleaned_data['email_apoteker']
			try:
				with connection.cursor() as c:
					c.execute("UPDATE transaksi_dengan_resep SET nama_dokter=%s, nama_pasien=%s, isi_resep=%s, unggahan_resep=%s, tanggal_resep=%s, status_validasi=%s, no_telepon=%s, id_transaksi_pembelian=%s, email_apoteker=%s WHERE no_resep = %s",
						[nama_dokter,nama_pasien,isi_resep,unggahan_resep,tanggal_resep,status_validasi,no_telepon,id_transaksi_pembelian,email_apoteker, no_resep])
				return HttpResponseRedirect(reverse('transaksi_resep:transaksi_dengan_resep'))
			except Exception as e:
				return HttpResponseRedirect(reverse('transaksi_resep:transaksi_dengan_resep'))
	with connection.cursor() as c :
		c.execute("SELECT * FROM TRANSAKSI_DENGAN_RESEP WHERE no_resep = %s", [no_resep])
		res = dictfetchall(c)
	initial_data = {
		'no_resep' : res[0]['no_resep'],
		'nama_dokter' : res[0]['nama_dokter'],
		'nama_pasien' : res[0]['nama_pasien'],
		'isi_resep' : res[0]['isi_resep'],
		'unggahan_resep' : res[0]['unggahan_resep'],
		'tanggal_resep' : res[0]['tanggal_resep'],
		'status_validasi' : res[0]['status_validasi'],
		'no_telepon' : res[0]['no_telepon'],
		'id_transaksi_pembelian' : res[0]['id_transaksi_pembelian'],
		'email_apoteker' : res[0]['email_apoteker']
	}
	update_form_resep = updateForm(initial=initial_data)
	response = {'update_form_resep':update_form_resep }
	return render(request,'update_transaksi_resep.html',response)

def delete_transaksi_resep(request, no_resep):
	with connection.cursor() as c:
		c.execute("DELETE FROM TRANSAKSI_DENGAN_RESEP WHERE no_resep = %s", [no_resep])
	return HttpResponseRedirect(reverse('transaksi_resep:transaksi_dengan_resep'))

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

transaksi_resep/templates/create_transaksi_resep.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buat Transaksi Dengan Resep</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <style>
        h1 {
            color: maroon;
            margin-top: 40px;
            margin-bottom: 40px;
            text-align: center;
        }
        
        body {
            background-color: linen;
            margin-left: 40px;
            margin-right: 50px;
        }
    </style>
</head>

<body>
    <div>
        <h1>Buat Transaksi Dengan Resep</h1>
    </div>
    <div>
        <form action='' method="POST">
            {% csrf_token %} {{ create_form_resep }}
            <div class="centre-items">
                <button type="submit" class="btn btn-primary" value="Update Transaksi dengan Resep">Submit</button>
            </div>
        </form>
    </div>
</body>

</html>

transaksi_resep/templates/transaksi_dengan_resep.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <style>
        h1 {
            color: maroon;
            margin-top: 40px;
            margin-bottom: 40px;
            text-align: center;
        }
        
        body {
            background-color: linen;
            margin-left: 40px;
            margin-right: 50px;
        }
    </style>
    <title>Info Transaksi Dengan Resep</title>
</head>

<body>
    <div class="page-header">
        <h1>Info Transaksi Dengan Resep</h1>
    </div>
    
    <a href="{% url 'profil:profil' %}" class="btn btn-danger"><b>Profil</b></a>
    {% if request.session.role == 'admin_apotek' %}
    <div class="pi-draggable btn-group" draggable="true">
        <a href="{% url 'transaksi_resep:create_transaksi_resep' %}" class="btn btn-danger"><b>Add</b></a>
    </div>
    {% elif request.session.role == 'cs'%}
    <div class="pi-draggable btn-group" draggable="true">
        <a href="{% url 'transaksi_resep:create_transaksi_resep' %}" class="btn btn-danger"><b>Add</b></a>
    </div>
    {% endif %}

    <div>
        <table class=' table table-condensed '>
            <thead>
                <tr>
                    <th>No Resep</th>
                    <th>Dokter</th>
                    <th>Pasien</th>
                    <th>Isi Resep</th>
                    <th>Unggahan Resep</th>
                    <th>Tanggal</th>
                    <th>Status</th>
                    <th>No Telepon</th>
                    <th>Transaksi</th> 
                    <th>Email Apoteker</th>
                    {% if request.session.role == 'admin_apotek' %}
                    <th>Action</th>
                    {% elif request.session.role == 'cs' %}
                    <th>Action</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for transaksi in data_transaksi_dengan_resep %}
                <tr>
                    <td>{{ transaksi.no_resep }}</td>
                    <td>{{ transaksi.nama_dokter }}</td>
                    <td>{{ transaksi.nama_pasien }}</td>
                    <td>{{ transaksi.isi_resep }}</td>
                    <td>{{ transaksi.unggahan_resep }}</td>
                    <td>{{ transaksi.tanggal_resep }}</td>
                    <td>{{ transaksi.status_validasi }}</td>
                    <td>{{ transaksi.no_telepon }}</td>
                    <td>{{ transaksi.id_transaksi_pembelian }}</td>
                    <td>{{ transaksi.email_apoteker }}</td>
                    {% if request.session.role == 'admin_apotek' %}
                    <td>
                        <div class="pi-draggable btn-group" draggable="true">
                            <a href="{% url 'transaksi_resep:update_transaksi_resep' no_resep=transaksi.no_resep %}" class="btn btn-primary"><b>Update</b></a>
                            <a href="{% url 'transaksi_resep:delete_transaksi_resep' no_resep=transaksi.no_resep %}" class="btn btn-danger"><b>Delete</b></a>
                        </div>
                    </td>
                    {% elif request.session.role == 'cs' %}
                    <td>
                        <div class="pi-draggable btn-group" draggable="true">
                            <a href="{% url 'transaksi_resep:update_transaksi_resep' no_resep=transaksi.no_resep %}" class="btn btn-primary"><b>Update</b></a>
                            <a href="{% url 'transaksi_resep:delete_transaksi_resep' no_resep=transaksi.no_resep %}" class="btn btn-danger"><b>Delete</b></a>
                        </div>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>

</html>

transaksi_resep/templates/update_transaksi_resep.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Transaksi dengan Resep</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <style>
        h1 {
            color: maroon;
            margin-top: 40px;
            margin-bottom: 40px;
            text-align: center;
        }
        
        body {
            background-color: linen;
            margin-left: 40px;
            margin-right: 50px;
        }
    </style>
</head>

<body>
    <div>
        <h1>Update Transaksi dengan Resep</h1>
    </div>
    <div>
        <form action='' method="POST" class="form-group">
            {% csrf_token %}
            {% for field in update_form_resep.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }} {{ field }}
            </div>
            {% endfor %}
            <div class="centre-items">
                <button type="submit" class="btn btn-primary" value="Update Transaksi dengan Resep">Update</button>
            </div>
        </form>
    </div>
</body>

</html>