alat_medis/urls.py
from django.urls import path
from .views import *

app_name = 'alat_medis'
urlpatterns = [
	path('', alat_medis, name='alat_medis'),
	path('create_alat_medis', create_alat_medis, name='create_alat_medis'),
	path('update_alat_medis/<str:id_alat_medis>/<str:id_produk>', update_alat_medis, name='update_alat_medis'),
	path('delete_alat_medis/<str:id_alat_medis>/<str:id_produk>', delete_alat_medis, name='delete_alat_medis')
]

farmakami/urls.py
from django.contrib import admin
from django.urls import path, include

import homepage.urls
import apotek.urls
import produk_apotek.urls
import login.urls
import alat_medis.urls
import balai_pengobatan.urls
import list_produk.urls
import obat.urls
import pengantaran_farmasi.urls
import profil.urls
import transaksi_pembelian.urls
import transaksi_resep.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(homepage.urls)),
    path('apotek/',include(apotek.urls)),
    path('produk_apotek/',include(produk_apotek.urls)),
    path('auth/',include(login.urls)),
    path('alat_medis/',include(alat_medis.urls)),
    path('balai_pengobatan/',include(balai_pengobatan.urls)),
    path('list_produk/',include(list_produk.urls)),
    path('obat/',include(obat.urls)),
    path('pengantaran_farmasi/',include(pengantaran_farmasi.urls)),
    path('profil/',include(profil.urls)),
    path('transaksi_pembelian/',include(transaksi_pembelian.urls)),
    path('transaksi_resep/',include(transaksi_resep.urls))
]

obat/urls.py
from django.urls import path
from .views import *

app_name = 'obat'
urlpatterns = [
	path('', rud_obat, name = 'rud_obat'),
	path('create_obat', create_obat, name = 'create_obat'),
	path('update_obat/<str:key>', update_obat, name = 'update_obat'),
	path('delete_obat/<str:key>', delete_obat, name = 'delete_obat')
]

profil/urls.py
from django.urls import path
from .views import *

app_name = 'profil'
urlpatterns = [
	path('', profil, name='profil')
]

alat_medis/models.py
from django.db import models

# Create your models here.

alat_medis/forms.py
from django import forms


class createForm(forms.Form):

    nama_alat_medis = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nama Alat Medis',
        'type' : 'text',
        'required': True,
    }))

    deskripsi_alat = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Deskripsi',
        'type' : 'text',
    }), required = False)

    jenis_penggunaan = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Jenis Penggunaan',
        'type' : 'text',
        'required': True,
    }))


class updateForm(forms.Form):

    id_alat_medis = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type' : 'text',
        'required': True,
        'readonly' : True,
    }))

    nama_alat_medis = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nama Alat Medis',
        'type' : 'text',
        'required': True,
    }))

    deskripsi_alat = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Deskripsi',
        'type' : 'text',
    }), required = False)

    jenis_penggunaan = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Jenis Penggunaan',
        'type' : 'text',
        'required': True,
    }))

    id_produk = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'Unggahan Resep',
        'required': True,
        'readonly' : True,
    }))

alat_medis/views.py
from django.shortcuts import render
from django.db import connection
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import *

# Create your views here.
def alat_medis(request):
    with connection.cursor() as c:
        c.execute("SELECT * FROM ALAT_MEDIS ORDER BY id_alat_medis ASC")
        res = dictfetchall(c)
    response = {'data_alat_medis':res}
    return render(request,'alat_medis.html',response)

def create_alat_medis(request):
    if request.method == 'POST' :
        form = createForm(request.POST)
        if form.is_valid():
            with connection.cursor() as c:
               c.execute("SELECT * FROM ALAT_MEDIS ORDER BY id_alat_medis desc limit 1")
               last_data = dictfetchall(c)
            last_id_am = last_data[0]['id_alat_medis']
            updated_last_am = int(last_id_am[2:])+1
            updated_last_am_str = '{:03d}'.format(updated_last_am)
            id_alat_medis = 'AM' + updated_last_am_str
            nama_alat_medis = form.cleaned_data['nama_alat_medis']
            deskripsi_alat = form.cleaned_data['deskripsi_alat']
            jenis_penggunaan = form.cleaned_data['jenis_penggunaan']
            with connection.cursor() as ci:
                ci.execute("SELECT * FROM PRODUK ORDER BY id_produk desc limit 1")
                last_data_produk = dictfetchall(ci)
            last_id_produk = last_data_produk[0]['id_produk']
            updated_last_produk = int(last_id_produk[3:])+1
            id_produk = 'KST' + str(updated_last_produk)
            with connection.cursor() as c:
                c.execute("INSERT INTO PRODUK VALUES ( %s )",[id_produk])
                c.execute("INSERT INTO ALAT_MEDIS VALUES( %s , %s , %s , %s , %s)",
                [id_alat_medis, nama_alat_medis, deskripsi_alat, jenis_penggunaan, id_produk])
        return HttpResponseRedirect(reverse('alat_medis:alat_medis'))
    create_form = createForm()
    response = {'create_form':create_form}
    return render(request,'create_alat_medis.html',response)

def update_alat_medis(request, id_alat_medis, id_produk):
    if request.method == 'POST':
        form = updateForm(request.POST)
        if form.is_valid():
            id_alat_medis = form.cleaned_data['id_alat_medis']
            nama_alat_medis = form.cleaned_data['nama_alat_medis']
            deskripsi_alat = form.cleaned_data['deskripsi_alat']
            jenis_penggunaan = form.cleaned_data['jenis_penggunaan']
            id_produk = form.cleaned_data['id_produk']
            with connection.cursor() as c:
                c.execute("""INSERT INTO ALAT_MEDIS VALUES ( %s , %s , %s , %s , %s) ON CONFLICT (id_alat_medis)
                    DO UPDATE SET nama_alat_medis = %s, deskripsi_alat = %s, jenis_penggunaan = %s""",
                    [id_alat_medis, nama_alat_medis, deskripsi_alat, jenis_penggunaan, id_produk,
                    nama_alat_medis, deskripsi_alat, jenis_penggunaan])
        return HttpResponseRedirect(reverse('alat_medis:alat_medis'))
    with connection.cursor() as c:
        c.execute("SELECT * FROM ALAT_MEDIS WHERE id_alat_medis = %s and id_produk = %s", [id_alat_medis, id_produk])
        res = dictfetchall(c)
    initial_data = {
        'id_alat_medis' : res[0]['id_alat_medis'],
        'nama_alat_medis' :res[0]['nama_alat_medis'],
        'deskripsi_alat' : res[0]['deskripsi_alat'],
        'jenis_penggunaan' : res[0]['jenis_penggunaan'],
        'id_produk' : res[0]['id_produk']
    }
    update_form = updateForm(initial=initial_data)
    response = {'update_form':update_form}
    return render(request,'update_alat_medis.html',response)

def delete_alat_medis(request, id_alat_medis, id_produk):
    with connection.cursor() as c:
        c.execute("DELETE FROM ALAT_MEDIS WHERE id_alat_medis = %s AND id_produk = %s",
            [id_alat_medis, id_produk])
        c.execute("DELETE FROM PRODUK WHERE id_produk = %s",['id_produk'])
    return HttpResponseRedirect(reverse('alat_medis:alat_medis'))

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

alat_medis/templates/alat_medis.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <style>
        h1 {
            color: maroon;
            margin-top: 40px;
            margin-bottom: 40px;
            text-align: center;
        }
        
        body {
            background-color: linen;
            margin-left: 40px;
            margin-right: 50px;
        }
    </style>
    <title>Info Alat Medis</title>
</head>

<body>
    <div class="page-header">
        <h1>Info Alat Medis</h1>
    </div>

    <a href="{% url 'profil:profil' %}" class="btn btn-danger"><b>Profil</b></a>
    {% if request.session.role == 'admin_apotek' %}
    <div class="pi-draggable btn-group" draggable="true">
        <a href="{% url 'alat_medis:create_alat_medis' %}" class="btn btn-danger"><b>Add</b></a>
    </div>
    {% elif request.session.role == 'cs'%}
    <div class="pi-draggable btn-group" draggable="true">
        <a href="{% url 'alat_medis:create_alat_medis' %}" class="btn btn-danger"><b>Add</b></a>
    </div>
    {% endif %}

    <div>
        <table class=' table table-condensed '>
            <thead>
                <tr>
                    <th>ID alat Medis</th>
                    <th>Nama Alat Medis</th>
                    <th>Deskripsi</th>
                    <th>Jenis Penggunaan</th>
                    <th>ID produk</th>
                    {% if request.session.role == 'admin_apotek' %}
                    <th>Action</th>
                    {% elif request.session.role == 'cs' %}
                    <th>Action</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for alat_medis in data_alat_medis %}
                <tr>
                    <td>{{ alat_medis.id_alat_medis }}</td>
                    <td>{{ alat_medis.nama_alat_medis }}</td>
                    <td>{{ alat_medis.deskripsi_alat }}</td>
                    <td>{{ alat_medis.jenis_penggunaan }}</td>
                    <td>{{ alat_medis.id_produk }}</td>
                    {% if request.session.role == 'admin_apotek' %}
                    <td>
                        <div class="pi-draggable btn-group" draggable="true">
                            <a href="{% url 'alat_medis:update_alat_medis' id_alat_medis=alat_medis.id_alat_medis id_produk=alat_medis.id_produk %}" class="btn btn-primary"><b>Update</b></a>
                            <a href="{% url 'alat_medis:delete_alat_medis' id_alat_medis=alat_medis.id_alat_medis id_produk=alat_medis.id_produk %}" class="btn btn-danger"><b>Delete</b></a>
                        </div>
                    </td>
                    {% elif request.session.role == 'cs' %}
                    <td>
                        <div class="pi-draggable btn-group" draggable="true">
                            <a href="{% url 'alat_medis:update_alat_medis' id_alat_medis=alat_medis.id_alat_medis id_produk=alat_medis.id_produk %}" class="btn btn-primary"><b>Update</b></a>
                            <a href="{% url 'alat_medis:delete_alat_medis' id_alat_medis=alat_medis.id_alat_medis id_produk=alat_medis.id_produk %}" class="btn btn-danger"><b>Delete</b></a>
                        </div>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>

</html>

alat_medis/templates/create_alat_medis.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buat Alat Medis</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <style>
        h1 {
            color: maroon;
            margin-top: 40px;
            margin-bottom: 40px;
            text-align: center;
        }
        
        body {
            background-color: linen;
            margin-left: 40px;
            margin-right: 50px;s
        }
    </style>
</head>

<body>
    <div>
        <h1>Buat Alat Medis</h1>
    </div>
    
    <div>
        <form action='' method="POST">
            {% csrf_token %} {{ create_form }}
            <div class="centre-items">
                <button type="submit" class="btn btn-primary" value="Create Alat Medis">Submit</button>
            </div>
        </form>
    </div>
</body>

</html>

alat_medis/templates/update_alat_medis.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Transaksi dengan Resep</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <style>
        h1 {
            color: maroon;
            margin-top: 40px;
            margin-bottom: 40px;
            text-align: center;
        }
        
        body {
            background-color: linen;
            margin-left: 40px;
            margin-right: 50px;
        }
    </style>
</head>

<body>
    <div>
        <h1>Update Alat Medis</h1>
    </div>
    
    <div class= "isi">
        <form action='' method="POST" class="form-group">
            {% csrf_token %}
            {% for field in update_form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }} {{ field }}
            </div>
            {% endfor %}
            <div class="centre-items">
                <button type="submit" class="btn btn-primary" value="Update Alat Medis">Update</button>
            </div>
        </form>
    </div>
</body>

</html>