balai_pengobatan/urls.py
from django.urls import path
from .views import *

app_name = 'balai_pengobatan'
urlpatterns = [
	path('', rud_balai_pengobatan, name = 'rud_balai_pengobatan'),
	path('create_balai_pengobatan', create_balai_pengobatan, name = 'create_balai_pengobatan'),
	path('update_balai_pengobatan/<str:key>', update_balai_pengobatan, name = 'update_balai_pengobatan'),
	path('delete_balai_pengobatan/<str:key>', delete_balai_pengobatan, name = 'delete_balai_pengobatan')
]

farmakami/urls.py
from django.contrib import admin
from django.urls import path, include

import homepage.urls
import apotek.urls
import produk_apotek.urls
import login.urls
import alat_medis.urls
import balai_pengobatan.urls
import list_produk.urls
import obat.urls
import pengantaran_farmasi.urls
import profil.urls
import transaksi_pembelian.urls
import transaksi_resep.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(homepage.urls)),
    path('apotek/',include(apotek.urls)),
    path('produk_apotek/',include(produk_apotek.urls)),
    path('auth/',include(login.urls)),
    path('alat_medis/',include(alat_medis.urls)),
    path('balai_pengobatan/',include(balai_pengobatan.urls)),
    path('list_produk/',include(list_produk.urls)),
    path('obat/',include(obat.urls)),
    path('pengantaran_farmasi/',include(pengantaran_farmasi.urls)),
    path('profil/',include(profil.urls)),
    path('transaksi_pembelian/',include(transaksi_pembelian.urls)),
    path('transaksi_resep/',include(transaksi_resep.urls))
]

obat/urls.py
from django.urls import path
from .views import *

app_name = 'obat'
urlpatterns = [
	path('', rud_obat, name = 'rud_obat'),
	path('create_obat', create_obat, name = 'create_obat'),
	path('update_obat/<str:key>', update_obat, name = 'update_obat'),
	path('delete_obat/<str:key>', delete_obat, name = 'delete_obat')
]

profil/urls.py
from django.urls import path
from .views import *

app_name = 'profil'
urlpatterns = [
	path('', profil, name='profil')
]

balai_pengobatan/models.py
from django.db import models

# Create your models here.

balai_pengobatan/forms.py
from django import forms
from django.db import connection

cursor = connection.cursor()
cursor.execute("SELECT id_apotek FROM FARMAKAMI.APOTEK")
select = cursor.fetchall()

id_apotek_berasosiasi = [tuple([select[x][0], select[x][0]]) for x in range(len(select))]


class createForm(forms.Form):

    alamat_balai = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Alamat Balai',
        'type' : 'text',
        'required': True,
    }))

    nama_balai = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nama Balai',
        'type' : 'text',
        'required': True,
    }))

    jenis_balai = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Jenis Balai',
        'type' : 'text',
        'required': True,
    }))

    telepon_balai = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'Telepon Balai',
        'required': False,
    }))

    id_apotek = forms.CharField(widget=forms.Select(choices=id_apotek_berasosiasi, attrs={
        'class': 'form-control',
        'placeholder' : 'Apotek Bersosiasi',
        'required': True,
    }))


class updateForm(forms.Form):

    id_balai  = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'ID Balai',
        'type' : 'text',
        'required': True,
        'readonly': True,
    }))
    
    alamat_balai = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Alamat Balai',
        'type' : 'text',
        'required': True,
    }))

    nama_balai = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nama Balai',
        'type' : 'text',
        'required': True,
    }))

    jenis_balai  = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Jenis Balai',
        'type' : 'text',
        'required': True,
    }))

    telepon_balai = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'Nomor Telepon Balai',
        'required': False,
    }))

    id_apotek = forms.CharField(widget=forms.Select(choices=id_apotek_berasosiasi, attrs={
        'class': 'form-control',
        'required': True,
    }))

balai_pengobatan/views.py
from django.shortcuts import render
from django.db import connection
from django.http import HttpResponseRedirect
from django.urls import reverse
from collections import namedtuple
from .forms import *

# Create your views here.
def rud_balai_pengobatan(request):
	with connection.cursor() as c:
		c.execute("SELECT bp.id_balai,alamat_balai,nama_balai,jenis_balai, telepon_balai, id_apotek FROM BALAI_PENGOBATAN as bp JOIN BALAI_APOTEK as ba ON bp.id_balai = ba.id_balai")
		res1 = dictfetchall(c)
	response = {'data_balai_pengobatan':res1}
	return render(request,'rud_balai_pengobatan.html', response)

def create_balai_pengobatan(request):
	if request.method == 'POST':
		form = createForm(request.POST)
		if form.is_valid():
			with connection.cursor() as ci:
				ci.execute("SELECT * FROM BALAI_PENGOBATAN ORDER BY id_balai desc limit 1")
				last_data = dictfetchall(ci)
			last_id = last_data[0]['id_balai']
			updated_id = int(last_id[2:]) + 1
			updated_id_str = '{:03d}'.format(updated_id)
			id_balai = 'BL' + updated_id_str
			alamat_balai = form.cleaned_data['alamat_balai']
			nama_balai = form.cleaned_data['nama_balai']
			jenis_balai = form.cleaned_data['jenis_balai']
			telepon_balai = form.cleaned_data['telepon_balai']
			id_apotek = form.cleaned_data['id_apotek']
			with connection.cursor() as c:
				c.execute("INSERT INTO BALAI_PENGOBATAN VALUES ( %s, %s, %s, %s, %s)", 
					[id_balai, alamat_balai, nama_balai, jenis_balai, telepon_balai])
				c.execute("INSERT INTO BALAI_APOTEK VALUES (%s, %s)",
					[id_balai, id_apotek])
		return HttpResponseRedirect(reverse('balai_pengobatan:rud_balai_pengobatan'))
	create_form = createForm()
	response = {'create_form' : create_form}
	return render(request, 'create_balai_pengobatan.html', response)

def update_balai_pengobatan(request, key):
	if request.method == 'POST':
		form = updateForm(request.POST)
		if form.is_valid():
			id_balai = form.cleaned_data['id_balai']
			alamat_balai = form.cleaned_data['alamat_balai']
			nama_balai = form.cleaned_data['nama_balai']
			jenis_balai = form.cleaned_data['jenis_balai']
			telepon_balai = form.cleaned_data['telepon_balai']
			id_apotek = form.cleaned_data['id_apotek']
			with connection.cursor() as c:
				c.execute("""INSERT INTO BALAI_PENGOBATAN VALUES ( %s, %s, %s, %s, %s) ON CONFLICT (id_balai)
					DO UPDATE SET alamat_balai = %s, nama_balai = %s, jenis_balai = %s, telepon_balai = %s""", 
					[id_balai, alamat_balai, nama_balai, jenis_balai, telepon_balai, alamat_balai, nama_balai, jenis_balai, telepon_balai])
				c.execute("UPDATE BALAI_APOTEK SET id_apotek = %s WHERE id_balai = %s", [id_apotek, key])
		return HttpResponseRedirect(reverse('balai_pengobatan:rud_balai_pengobatan'))	
	with connection.cursor() as c:
		c.execute("SELECT bp.id_balai,alamat_balai,nama_balai,jenis_balai, telepon_balai, id_apotek FROM BALAI_PENGOBATAN as bp JOIN BALAI_APOTEK as ba ON bp.id_balai = ba.id_balai WHERE bp.id_balai = %s", [key])
		res = dictfetchall(c)
	initial_data = {
		'id_balai' : res[0]['id_balai'],
		'alamat_balai' : res[0]['alamat_balai'],
		'nama_balai' : res[0]['nama_balai'],
		'jenis_balai' : res[0]['jenis_balai'],
		'telepon_balai' : res[0]['telepon_balai'],
		'id_apotek' : res[0]['id_apotek'],
	}
	update_form = updateForm(initial = initial_data)
	response = {'update_form' : update_form}
	return render(request,'update_balai_pengobatan.html', response)

def delete_balai_pengobatan(request, key):
	with connection.cursor() as c:
		c.execute("DELETE FROM BALAI_PENGOBATAN WHERE id_balai = %s", [key])
		c.execute("DELETE FROM BALAI_APOTEK WHERE id_balai = %s", [key])
		return HttpResponseRedirect(reverse('balai_pengobatan:rud_balai_pengobatan'))

def dictfetchall(cursor):
	"Return all rows from a cursor as a dict"
	columns = [col[0] for col in cursor.description]
	return [
		dict(zip(columns, row))
		for row in cursor.fetchall()
	]

balai_pengobatan/templates/create_balai_pengobatan.html
<html lang="en">

<head>
<title>Create Balai Pengobatan</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <style>
        h1 {
        color: maroon;
        margin-top: 40px;
        margin-bottom: 40px;
        text-align: center;
        }

        body {
        background-color: linen;
        margin-left: 40px;
        margin-right: 50px;
        }
    </style>
</head>

<body>
    <div>
        <h1>Create Balai Pengobatan</h1>
    </div>
    <div>
        <form method="POST">
        {% csrf_token %}
            <div class="form-group">
                {{ create_form }}
            </div>
            <div class="centre-items">
                <input type="submit" class="btn btn-primary" value="Create Balai Pengobatan">
            </div>
        </form>
    </div>
</body>

</html>

balai_pengobatan/templates/rud_balai_pengobatan.html
<html lang="en">

<head>
    <title>Informasi Balai Pengobatan</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <style>
        h1 {
        color: maroon;
        margin-top: 40px;
        margin-bottom: 40px;
        text-align: center;
        }

        body {
        background-color: linen;
        margin-left: 40px;
        margin-right: 50px;
        }
    </style>
</head>

<body>
    <div class="page-header">
        <h1>Informasi Balai Pengobatan</h1>
    </div>

    <a href="{% url 'profil:profil' %}" class="btn btn-danger"><b>Profil</b></a>
    {% if request.session.role == 'admin_apotek' %}
    <div class="pi-draggable btn-group" draggable="true">
        <a href="{% url 'balai_pengobatan:create_balai_pengobatan' %}" class="btn btn-danger"><b>Create</b></a>
    </div>
    {% endif %}
    
    <div>
        <table class=' table table-condensed '>
            <thead>
                <tr>
                    <th>ID Balai</th>
                    <th>Alamat Balai</th>
                    <th>Nama Balai</th>
                    <th>Jenis Balai</th>
                    <th>No. Telpon Balai</th>
                    <th>Apotek yang berasosiasi</th>
                    {% if request.session.role == 'admin_apotek' %}
                    <th>Action</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for balai_pengobatan in data_balai_pengobatan %}
                <tr>
                    <td>{{ balai_pengobatan.id_balai }}</td>
                    <td>{{ balai_pengobatan.alamat_balai }}</td>
                    <td>{{ balai_pengobatan.nama_balai }}</td>
                    <td>{{ balai_pengobatan.jenis_balai }}</td>
                    <td>{{ balai_pengobatan.telepon_balai }}</td>
                    <td>{{ balai_pengobatan.id_apotek }}</td>
                    {% if request.session.role == 'admin_apotek' %}
                    <td>
                    <div class="pi-draggable btn-group" draggable="true">
                        <a class="btn btn-primary" href="{% url 'balai_pengobatan:update_balai_pengobatan' key=balai_pengobatan.id_balai %}"><b>Update</b></a>
                        <a class="btn btn-danger" href="{% url 'balai_pengobatan:delete_balai_pengobatan' key=balai_pengobatan.id_balai %}"><b>Delete</b></a>
                    </div>
                    {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>

</html>

balai_pengobatan/templates/update_balai_pengobatan.html
<html lang="en">

<head>
    <title>Update Balai Pengobatan</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <style>
        h1 {
        color: maroon;
        margin-top: 40px;
        margin-bottom: 40px;
        text-align: center;
        }

        body {
        background-color: linen;
        margin-left: 40px;
        margin-right: 50px;
        }
    </style>
</head>

<body>
    <div>
        <h1>Update Balai Pengobatan</h1>
    </div>
    <div>
        <form action='' method="POST">
        {% csrf_token %}
        {% for field in update_form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }} {{ field }}
            </div>
        {% endfor %}
        <div class="centre-items">
            <button type="submit" class="btn btn-primary" value="Update Balai Pengobatan">Update</button>
        </div>
        </form>
    </div>
</body>

</html>