farmakami/urls.py
from django.contrib import admin
from django.urls import path, include

import homepage.urls
import apotek.urls
import produk_apotek.urls
import login.urls
import alat_medis.urls
import balai_pengobatan.urls
import list_produk.urls
import obat.urls
import pengantaran_farmasi.urls
import profil.urls
import transaksi_pembelian.urls
import transaksi_resep.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(homepage.urls)),
    path('apotek/',include(apotek.urls)),
    path('produk_apotek/',include(produk_apotek.urls)),
    path('auth/',include(login.urls)),
    path('alat_medis/',include(alat_medis.urls)),
    path('balai_pengobatan/',include(balai_pengobatan.urls)),
    path('list_produk/',include(list_produk.urls)),
    path('obat/',include(obat.urls)),
    path('pengantaran_farmasi/',include(pengantaran_farmasi.urls)),
    path('profil/',include(profil.urls)),
    path('transaksi_pembelian/',include(transaksi_pembelian.urls)),
    path('transaksi_resep/',include(transaksi_resep.urls))
]

obat/urls.py
from django.urls import path
from .views import *

app_name = 'obat'
urlpatterns = [
	path('', rud_obat, name = 'rud_obat'),
	path('create_obat', create_obat, name = 'create_obat'),
	path('update_obat/<str:key>', update_obat, name = 'update_obat'),
	path('delete_obat/<str:key>', delete_obat, name = 'delete_obat')
]

profil/urls.py
from django.urls import path
from .views import *

app_name = 'profil'
urlpatterns = [
	path('', profil, name='profil')
]

obat/models.py
from django.db import models

# Create your models here.

obat/forms.py
from django import forms
from django.db import connection


c = connection.cursor()
c.execute("SELECT id_merk_obat FROM FARMAKAMI.MERK_OBAT")
select_merkob = c.fetchall()

opt_id_merk_obat = [tuple([select_merkob[x][0], select_merkob[x][0]]) for x in range(len(select_merkob))]

class createForm(forms.Form):

    id_merk_obat = forms.CharField(widget=forms.Select(choices=opt_id_merk_obat, attrs={
        'class': 'form-control',
        'placeholder': 'ID Merk Obat', 
        'required': True,
    }))

    netto = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Netto',
        'type' : 'text',
        'required': True,
    }))

    dosis = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Dosis',
        'type' : 'text',
        'required': True,
    }))

    aturan_pakai = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Aturan Pakai',
        'type' : 'text',
        'required': False,
    }))

    kontraindaksi = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Kontraindaksi',
        'type' : 'text',
        'required': False,
    }))

    bentuk_kesediaan = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Bentuk Kesediaan',
        'type' : 'text',
        'required': True,
    }))

class updateForm(forms.Form):

    id_obat = forms.CharField(widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'ID Obat',
            'type' : 'text',
            'required': True,
            'readonly' : True,
    }))

    id_produk = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'ID Produk',
        'type' : 'text',
        'required': True,
        'readonly' : True,
    }))

    id_merk_obat = forms.CharField(widget=forms.Select(choices=opt_id_merk_obat, attrs={
        'class': 'form-control',
        'placeholder': 'ID Merk Obat', 
        'required': True,
    }))

    netto = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Netto',
        'type' : 'text',
        'required': True,
    }))

    dosis = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Dosis',
        'type' : 'text',
        'required': True,
    }))

    aturan_pakai = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Aturan Pakai',
        'type' : 'text',
        'required': False,
    }))

    kontraindaksi = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Kontraindaksi',
        'type' : 'text',
        'required': False,
    }))

    bentuk_kesediaan = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Bentuk Kesediaan',
        'type' : 'text',
        'required': True,
    }))

obat/views.py
from django.shortcuts import render
from django.db import connection
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import *

# Create your views here.
def rud_obat(request):
	with connection.cursor() as c:
		c.execute("SELECT * FROM OBAT ORDER BY id_obat ASC")
		res = dictfetchall(c)
	response = {'data_obat': res}
	return render(request,'rud_obat.html', response)

def create_obat(request):
	if  request.method == 'POST':
		form = createForm(request.POST)
		if form.is_valid():
			with connection.cursor() as c:
				c.execute("SELECT * from OBAT ORDER BY id_obat desc limit 1")
				last_data_obat = dictfetchall(c)
			last_id_obat = last_data_obat[0]['id_obat']
			updated_id_obat = int(last_id_obat[3:]) + 1
			updated_id_obat_str = '{:03d}'.format(updated_id_obat)
			id_obat = 'OBT' + updated_id_obat_str
			with connection.cursor() as ci:
				ci.execute("SELECT * from OBAT ORDER BY id_produk desc limit 1")
				last_data_produk = dictfetchall(ci)
			last_id_produk = last_data_produk[0]['id_produk']
			updated_id_produk = int(last_id_produk[3:]) + 1
			updated_id_produk_str = '{:02d}'.format(updated_id_produk)
			id_produk = 'KST' + updated_id_produk_str
			id_merk_obat = form.cleaned_data['id_merk_obat']
			netto = form.cleaned_data['netto']
			dosis = form.cleaned_data['dosis']
			aturan_pakai = form.cleaned_data['aturan_pakai']
			kontraindaksi = form.cleaned_data['kontraindaksi']
			bentuk_kesediaan = form.cleaned_data['bentuk_kesediaan']
			with connection.cursor() as ca:
				ca.execute("INSERT INTO OBAT VALUES ( %s, %s, %s, %s, %s, %s, %s, %s)",
					[id_obat, id_produk, id_merk_obat, netto, dosis, aturan_pakai, kontraindaksi, bentuk_kesediaan])
		return HttpResponseRedirect(reverse('obat:rud_obat'))
	create_form_obat = createForm()
	response = {'create_form' : create_form_obat}
	return render(request, 'create_obat.html', response)
	

def update_obat(request, key):
	if request.method == 'POST':
		form = updateForm(request.POST)
		if form.is_valid():
			id_obat = form.cleaned_data['id_obat']
			id_produk = form.cleaned_data['id_produk']
			id_merk_obat = form.cleaned_data['id_merk_obat']
			netto = form.cleaned_data['netto']
			dosis = form.cleaned_data['dosis']			
			aturan_pakai = form.cleaned_data['aturan_pakai']
			kontraindaksi = form.cleaned_data['kontraindaksi']
			bentuk_kesediaan = form.cleaned_data['bentuk_kesediaan']
			with connection.cursor() as c:
				c.execute("""INSERT INTO OBAT VALUES ( %s, %s, %s, %s, %s, %s, %s, %s) ON CONFLICT (id_obat)
					DO UPDATE SET id_merk_obat = %s, netto = %s, dosis = %s, aturan_pakai = %s, kontraindaksi = %s, bentuk_kesediaan = %s""", 
					[id_obat, id_produk, id_merk_obat, netto, dosis, aturan_pakai, kontraindaksi, bentuk_kesediaan, id_merk_obat, netto, dosis, aturan_pakai, kontraindaksi, bentuk_kesediaan])
		return HttpResponseRedirect(reverse('obat:rud_obat'))
	with connection.cursor() as c:
		c.execute("SELECT * FROM OBAT WHERE id_obat = %s", [key])
		res = dictfetchall(c)
	initial_data = {
		'id_obat' : res[0]['id_obat'],
		'id_produk' : res[0]['id_produk'],
		'id_merk_obat' : res[0]['id_merk_obat'],
		'netto' : res[0]['netto'],
		'dosis' : res[0]['dosis'],
		'aturan_pakai' : res[0]['aturan_pakai'],
		'kontraindaksi' : res[0]['kontraindaksi'],
		'bentuk_kesediaan' : res[0]['bentuk_kesediaan'],
	}
	update_form = updateForm(initial = initial_data)
	response = {'update_form' : update_form}
	return render(request,'update_obat.html', response)

def delete_obat(request, key):
	with connection.cursor() as c:
		c.execute("DELETE FROM OBAT WHERE id_obat = %s", [key])
		return HttpResponseRedirect(reverse('obat:rud_obat'))

def dictfetchall(cursor):
	"Return all rows from a cursor as a dict"
	columns = [col[0] for col in cursor.description]
	return [
	dict(zip(columns, row))
	for row in cursor.fetchall()
	]

obat/templates/create_obat.html
<html lang="en">

    <head>
        <title>Create Obat</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <style>
            h1 {
            color: maroon;
            margin-top: 40px;
            margin-bottom: 40px;
            text-align: center;
            }

            body {
            background-color: linen;
            margin-left: 40px;
            margin-right: 50px;
            }
        </style>
    </head>

    <body>
    <div>
        <h1>Create Obat</h1>
    </div>
    <div>
        <form method="POST">
            {% csrf_token %}
                <div class="form-group">
                    {{ create_form }} 
                </div>
            <div class="centre-items">
                <input type="submit" class="btn btn-primary" value="Create Obat">
            </div>
        </form>
    </div>
    </body>

</html>

obat/templates/rud_obat.html
<html lang="en">

    <head>
    <title>Informasi Obat</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <style>
        h1 {
        color: maroon;
        margin-top: 40px;
        margin-bottom: 40px;
        text-align: center;
        }

        body {
        background-color: linen;
        margin-left: 40px;
        margin-right: 50px;
        }
    </style>
    </head>

    <body>
        <div class="page-header">
            <h1>Informasi Obat</h1>
        </div>

        <a href="{% url 'profil:profil' %}" class="btn btn-danger"><b>Profil</b></a>
        {% if request.session.role == 'admin_apotek' %}
        <div class="pi-draggable btn-group" draggable="true">
            <a href="{% url 'obat:create_obat' %}" class="btn btn-danger"><b>Create</b></a>
        </div>
        {% endif %}
    
        <div>
            <table class=' table table-condensed '>
                <thead>
                    <tr>
                        <th>ID Obat</th>
                        <th>ID Produk</th>
                        <th>ID Merk Obat</th>
                        <th>Netto</th>
                        <th>Dosis</th>
                        <th>Aturan Pakai</th>
                        <th>Kontraindaksi</th>
                        <th>Bentuk Kesediaan</th>
                        {% if request.session.role == 'admin_apotek' %}
                        <th>Action</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                {% for obat in data_obat %} 
                <tr>
                    <td>{{ obat.id_obat }}</td>
                    <td>{{ obat.id_produk }}</td>
                    <td>{{ obat.id_merk_obat }}</td>
                    <td>{{ obat.netto }}</td>
                    <td>{{ obat.dosis }}</td>
                    <td>{{ obat.aturan_pakai }}</td>
                    <td>{{ obat.kontraindaksi }}</td>
                    <td>{{ obat.bentuk_kesediaan }}</td>
                    {% if request.session.role == 'admin_apotek' %}
                    <td>
                        <div class="pi-draggable btn-group" draggable="true">
                            <a class="btn btn-primary" href="{% url 'obat:update_obat' key=obat.id_obat %}"><b>Update</b></a>
                            <a class="btn btn-danger" href="{% url 'obat:delete_obat' key=obat.id_obat %}"><b>Delete</b></a>
                        </div>
                    {% endif %}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </body>

</html>

obat/templates/update_obat.html
<html lang="en">

<head>
    <title>Update Obat</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style>
        h1 {
        color: maroon;
        margin-top: 40px;
        margin-bottom: 40px;
        text-align: center;
        }

        body {
        background-color: linen;
        margin-left: 40px;
        margin-right: 50px;
        }
    </style>
</head>

<body>
    <div>
        <h1>Update Obat</h1>
    </div>
    <div>
        <form action='' method="POST">
        {% csrf_token %}
        {% for field in update_form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }} {{ field }}
        </div>
        {% endfor %}
        <div class="centre-items">
            <button type="submit" class="btn btn-primary" value="Update Balai Pengobatan">Update</button>
        </div>
        </form>
    </div>
</body>

</html>